environment:
  id: "Taxi-v3"

monitor:
  monitor_reset_prob: 0.5
  monitor_cost: 0.01

critic:
  q0: 0
  gamma: 0.99
  lr: 0.1
  use_reward_model: True
  reward_model:
    r0: 0
    lr: 1.

actor:
  init_eps: 0.8
  min_eps: 0.2
  eps_decay: 0.0005

experiment:
  training_episodes: 6000
  testing_episodes: 50
  testing_frequency: 10
  rng_seed: 1
