defaults:
  - agent: q_learning
  - monitor: state
  - _self_

environment:
  id: gym_monitor/TreasureHunt-Button-v1
  random_action_prob: 0.0

wandb:
  mode: offline
  entity: ualberta-bowling
  project: MonMDP

experiment:
  training_timesteps: 25e6
  testing_episodes: 50
  testing_frequency: 1e6
  rng_seed: 1
  save_log: True
