defaults:
  - exp: taxi_ql
  - _self_

wandb:
  mode: "offline"
  entity: "ualberta-bowling"
  project: "mmdp simone"

hydra:
  sweeper:
    params:
      exp.experiment.rng_seed: range(0, 5)
      exp.critic.lr: 0.001, 0.01, 0.5, 1.
      exp.critic.q0: 0., 1., 10., 50.
      exp.actor.eps_decay: 0.01, 0.001, 0.0001, 0.00001
