defaults:
  - agent: q_learning
  - monitor: binary
  - _self_

environment:
  id: gym_monitor/TreasureHunt-Penalty-v0
  random_action_prob: 0.05

wandb:
  mode: offline
  entity: ualberta-bowling
  project: mmdp

experiment:
  training_timesteps: 250000
  testing_timesteps: 100
  testing_frequency: 10000
  rng_seed: 1
  save_log: True

hydra:
  sweeper:
    params:
      experiment.rng_seed: range(0, 30)
#      agent.critic.strategy: reward_model, q_monitor_joint
      # environment.id: MiniGrid-DoorKey-5x5-v0, Taxi-v3
      # monitor.id: BinaryMonitor
#      monitor.monitor_reset_prob: 0., 0.1, 0.5, 1.
      # monitor.monitor_cost: 0., 0.01, 0.1, 0.5
      # agent.critic.lr: 0.01, 0.1, 1.
      # agent.critic.q0: 0., 1., 10.
      # agent.actor.eps_decay: 0.01, 0.001, 0.0001
