defaults:
  - agent: q_learning
  - monitor: binary
  - _self_

environment:
  id: gym_monitor/TreasureHunt-Fire-v0

wandb:
  mode: offline
  entity: ualberta-bowling
  project: MonMDP

experiment:
  training_timesteps: 250000
  testing_timesteps: 50
  testing_frequency: 100
  rng_seed: 1
  save_log: True
