defaults:
  - agent: q_learning
  - monitor: binary
  - _self_

environment:
  id: gym_monitor/TreasureHunt-Penalty-v1
  random_action_prob: 0.0

wandb:
  mode: offline
  entity: ualberta-bowling
  project: MonMDP

experiment:
  training_timesteps: 250000
  testing_timesteps: 100
  testing_frequency: 10000
  rng_seed: 1
  save_log: True
