environment:
  id: "Taxi-v3"

critic:
   init_q_values: 0
   gamma: 0.99
   lr: 0.1

actor:
   init_eps: 1.
   min_eps: 0.1
   eps_decay: 0.0001

experiment:
   training_episodes: 10000
   testing_episodes: 50
   testing_frequency: 10
   rng_seed: 1
