environment:
  id: "Taxi-v3"

critic:
  q0: 0
  gamma: 0.99
  lr: 0.1

actor:
  init_eps: 0.8
  min_eps: 0.2
  eps_decay: 0.0005

experiment:
  training_episodes: 10000
  testing_episodes: 50
  testing_frequency: 10
  rng_seed: 1
