critic:
  on_policy: False
  q0: 0
  gamma: 0.99
  lr: 1e-3 # 1.0
  strategy: q_learning
  unseen_r_value: 0.0
  reward_model:
    r0: 0
    lr: 1e-3 #1.0

actor:
  init_eps: 1.0
  min_eps: 1.0
  eps_decay: 0 # 4.5e-6
